apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: l3hentoti-nodejs 
  janus-idp.io/tekton: l3hentoti-nodejs
  backstage.io/kubernetes-id: l3hentoti-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: l3hentoti-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  